// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98ZnKA1oOWXxdCAvV1v2bZbGWDRy3BQA',
    appId: '1:134006927532:web:02540bc4751c50c6b46f09',
    messagingSenderId: '134006927532',
    projectId: 'androidcoursesashadaniel',
    authDomain: 'androidcoursesashadaniel.firebaseapp.com',
    storageBucket: 'androidcoursesashadaniel.firebasestorage.app',
    measurementId: 'G-YTV6PR7R88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVR6t0bM5h3QYBCFd_e7_apTnf9Bn-1c4',
    appId: '1:134006927532:android:8ccc73fb250c0ab3b46f09',
    messagingSenderId: '134006927532',
    projectId: 'androidcoursesashadaniel',
    storageBucket: 'androidcoursesashadaniel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRGt6FBR66cW9Q12rMVezUq1AjAj20ag4',
    appId: '1:134006927532:ios:1879c68e5be21d1cb46f09',
    messagingSenderId: '134006927532',
    projectId: 'androidcoursesashadaniel',
    storageBucket: 'androidcoursesashadaniel.firebasestorage.app',
    iosBundleId: 'com.example.childrenBooksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRGt6FBR66cW9Q12rMVezUq1AjAj20ag4',
    appId: '1:134006927532:ios:1879c68e5be21d1cb46f09',
    messagingSenderId: '134006927532',
    projectId: 'androidcoursesashadaniel',
    storageBucket: 'androidcoursesashadaniel.firebasestorage.app',
    iosBundleId: 'com.example.childrenBooksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC98ZnKA1oOWXxdCAvV1v2bZbGWDRy3BQA',
    appId: '1:134006927532:web:ad333330578cab7eb46f09',
    messagingSenderId: '134006927532',
    projectId: 'androidcoursesashadaniel',
    authDomain: 'androidcoursesashadaniel.firebaseapp.com',
    storageBucket: 'androidcoursesashadaniel.firebasestorage.app',
    measurementId: 'G-HEC82N49NE',
  );
}
